Adds some Qubes-specific docs to README
freedomofpress/kernel-builder pull request #17
Opened 2021-08-04 18:41 UTC by conorsch

Aiming to help others, particularly SecureDrop maintainers,
get started with a minimum of fuss.

2021-08-12 04:41 UTC, creviera requested changes

2021-08-12 04:41 UTC, creviera commented on README.md
> +the private volume is used for the build:
it would be helpful to mention that you'll be using bind-dirs and link to https://www.qubes-os.org/doc/bind-dirs/ for more info

2021-08-12 04:41 UTC, creviera commented on README.md
> +$ cat /rw/config/qubes-bind-dirs.d/50_user.conf
Enumerating instructions might be helpful here, like so:

1. Create a bind-dirs directory and a new file called '50_user.conf'
```
sudo mkdir /rw/config/qubes-bind-dirs.d
sudo vi /rw/config/qubes-bind-dirs.d/50_user.conf
```
2. Edit '50_user.conf' to append '/var/lib/docker' to the binds variable:
```
binds+=( '/var/lib/docker' )
```
3. Reboot the AppVM
```
sudo reboot
```

2021-08-12 04:41 UTC, creviera commented on README.md
> +source ~/grsec-env # credentials for grsecurity access
maybe a note that you'll need to request from a maintainer for these credentials and any pre-steps to create grsec-env

2021-08-13 19:46 UTC, creviera commented on README.md
> +The build requires `docker`, so make sure your TemplateVM has docker configured.
Could you also link to `#enabling-grsecurity-patches` and mention that you'll need to export a few environment variables with the grsec credentials. I think the `#enabling-grsecurity-patches` section also might need updating to include the `GRSECURITY` env var.

2021-08-13 19:48 UTC, creviera commented on README.md
> +The build requires `docker`, so make sure your TemplateVM has docker configured.
The `#enabling-grsecurity-patches` section should probably mention that you need to make a request for these credentials if you don't have them and to make sure to store them securely in your password manager.

2021-08-13 19:51 UTC, creviera commented on README.md
> +# grab a coffee or tea, builds take ~1h with 4 cores.
i like this note

2021-08-14 00:45 UTC, creviera commented
@conorsch - Just a note that I finished the process of building the kernel and am finished with my review. The logs are massive so we might want to explain in the docs how to store those logs automatically to file so that you can just copy them to the build-logs repo.

```
user@sd-kernel-builder:~/kernel-builder$ sha256sum build/linux-*
ed5d3c15fcdf28bae7e389d39a362b68f35b4b60ce0ac47af25eafec5b564b82  build/linux-4.14.243-grsec-workstation_4.14.243-grsec-workstation-1.debian.tar.gz
22d08bd63144ae2ba34978b3c8b148b2117433ef95176a225194b8de4120c66d  build/linux-4.14.243-grsec-workstation_4.14.243-grsec-workstation.orig.tar.gz
cbac647d467f5e9d48373e417b2b4416a7ea23ce616846fda4978af1c7e26d8e  build/linux-headers-4.14.243-grsec-workstation_4.14.243-grsec-workstation-1_amd64.deb
10c928116c4c3d11d974416feb34dbe147ef9a709b3460d3961938d9b0bf2600  build/linux-image-4.14.243-grsec-workstation_4.14.243-grsec-workstation-1_amd64.deb
0eae6ac70e0d78b73d2fae5d3df73d06a919ba336a752a9acbca178a670ee506  build/linux-image-4.14.243-grsec-workstation-dbg_4.14.243-grsec-workstation-1_amd64.deb
c1ec0fe54df5858e8eb4913432de5ff4ea86fdc110b18243c035874b887cb6d1  build/linux-libc-dev_4.14.243-grsec-workstation-1_amd64.deb

```

2021-08-17 14:14 UTC, conorsch commented
> The logs are massive so we might want to explain in the docs how to store those logs automatically to file so that you can just copy them to the build-logs repo.

True! I only recently discovered the menu option to "select all" in gnome terminal myself, as a way to side-step minutes of backscrolling. Will add a note about that, while addressing the other comments you left in your thoughtful review.

2021-08-17 21:07 UTC, conorsch commented
@creviera I've addressed all of the changes you requested. Please have another look!

2021-08-18 17:31 UTC, creviera approved these changes
all comments addressed

2021-08-18 17:31 UTC, merged